export const observable_analyzers = [
  { name: 'MISPFIRST', observable_supported: ['ip', 'domain', 'url', 'hash'] },
  { name: 'MISP', observable_supported: ['ip', 'domain', 'url', 'hash'] },
  { name: 'TorProject', observable_supported: ['ip'] },
  { name: 'Fortiguard', observable_supported: ['domain', 'url'] },
  { name: 'AbuseIPDB', observable_supported: ['ip'] },
  { name: 'MaxMindGeoIP', observable_supported: ['ip'] },
  { name: 'CIRCLPassiveSSL', observable_supported: ['ip'] },
  { name: 'CIRCLPassiveDNS', observable_supported: ['domain', 'url'] },
  { name: 'GreyNoiseAlpha', observable_supported: ['ip'] },
  {
    name: 'GoogleSafebrowsing',
    observable_supported: ['domain', 'url', 'ip'],
  },
  { name: 'Robtex_IP_Query', observable_supported: ['ip'] },
  { name: 'Shodan', observable_supported: ['ip'] },
  { name: 'Robtex_Reverse_PDNS_Query', observable_supported: ['ip'] },
  {
    name: 'Robtex_Forward_PDNS_Query',
    observable_supported: ['domain', 'url'],
  },
  { name: 'DNSDB', observable_supported: ['domain', 'url', 'ip'] },
  { name: 'TalosReputation', observable_supported: ['ip'] },
  { name: 'OTXQuery', observable_supported: ['ip', 'domain', 'url', 'hash'] },
  {
    name: 'VirusTotal_v2_Get_Observable',
    observable_supported: ['ip', 'domain', 'url', 'hash'],
  },
  {
    name: 'VirusTotal_v3_Get_Observable',
    observable_supported: ['ip', 'domain', 'url', 'hash'],
  },
  {
    name: 'HybridAnalysis_Get_Observable',
    observable_supported: ['ip', 'domain', 'url', 'hash'],
  },
  { name: 'HoneyDB', observable_supported: ['ip'] },
  { name: 'Hunter', observable_supported: ['domain'] },
];

export const file_analyzers = [
  { name: 'Yara_Scan_Community' },
  { name: 'Yara_Scan_Florian' },
  { name: 'Yara_Scan_Intezer' },
  { name: 'HybridAnalysis_Get_File', run_hash: true },
  { name: 'OTX_Check_Hash', run_hash: true },
  { name: 'MISPFIRST_Check_Hash', run_hash: true },
  { name: 'MISP_Check_Hash' },
  { name: 'Cuckoo_Scan' },
  {
    name: 'Intezer_Scan',
    supported_filetypes: ['application/x-dosexec'],
    leaks_info: true,
  },
  { name: 'VirusTotal_v2_Get_File_Alternative', run_hash: true },
  { name: 'VirusTotal_v2_Scan_File_Alternative', leaks_info: true },
  { name: 'VirusTotal_v3_Get_File_Alternative', run_hash: true },
  { name: 'VirusTotal_v3_Scan_File_Alternative', leaks_info: true },
  { name: 'VirusTotal_v2_Get_File', run_hash: true },
  { name: 'VirusTotal_v2_Scan_File', leaks_info: true },
  { name: 'VirusTotal_v3_Get_File', run_hash: true },
  { name: 'VirusTotal_v3_Get_File_And_Scan', run_hash: true },
  { name: 'VirusTotal_v3_Scan_File', leaks_info: true },
  { name: 'File_Info' },
  { name: 'Strings_Info_ML' },
  { name: 'Strings_Info_Classic' },
  { name: 'PE_Info', supported_filetypes: ['application/x-dosexec'] },
  { name: 'Signature_Info', supported_filetypes: ['application/x-dosexec'] },
  {
    name: 'Doc_Info',
    supported_filetypes: [
      'application/msword',
      'application/vnd.ms-office',
      'application/vnd.ms-excel.addin.macroEnabled',
      'application/x-mspublisher',
      'application/vnd.ms-powerpoint',
      'application/vnd.ms-excel',
      'application/vnd.ms-excel.sheet.macroEnabled.12',
      'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
      'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
      'application/vnd.openxmlformats-officedocument.presentationml.presentation',
      'text/x-ms-iqy',
      'application/excel',
      'text/xml',
      'application/xml',
    ],
  },
  { name: 'Rtf_Info', supported_filetypes: ['text/rtf', 'application/rtf'] },
  { name: 'PDF_Info', supported_filetypes: ['application/pdf'] },
];
